# Site settings
title: Simplexity
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Simplexity is a minimalistic theme for Jekyll. It is ment to showcase your
  content, using a monochrome color scheme and a fluid and responsive design.
  Large, legible fonts scale well across devices and various viewport sizes.
  Simplexity is licensed under MIT license.
# This would allow for more custom description markup.
#description_include: description.html
baseurl: "/simplexity" # the subpath of your site, e.g. /blog/
url: "http://matei.dorobantu.me/simplexity" # the base hostname & protocol for your site
show_post_excerpt: true

# Social
twitter: mateid
github: mateid
google: MateiDorobantu
#stackoverflow:

# Disquss comments
#disquss: mateid

# Analytics
#google_analytics

# Build settings
exclude: [node_modules, gulpfile.js, basscss]
markdown: kramdown
permalink: pretty
paginate: 3
sass:
 style: compressed

# Highlighting
highlighter: pygments
