# Site settings
title: Simplexity
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Simplexity is a minimalistic theme for jekyll. It is ment to showcase your content, using a monochrome
  design and large, legible fonts that scale well across devices. Simplexity is licensed under MIT license. Linkbacks
  are always appreciated!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://github.com/mateid/simplexity" # the base hostname & protocol for your site
twitter_username: mateid
github_username:  mateid
linkedin:

exclude: [node_modules, gulpfile.js, basscss]

# Build settings
markdown: kramdown
permalink:  pretty
paginate:  3
sass:
  style: compressed

# Highlighting
highlighter: pygments

